const aiModels = [
  {
    name: "ROH-Emo-1.0",
    Description: "AI with emotional Intelligence",
    Appearance: "2D/3D human-like form with emotional expressions",
    VoiceTone: "Adapts tone based on user emotions",
    Languages: "Supports multiple Languages with sentiment analysis",
    Speed: "Real-time emotional recognition and responses",
    Intelligence: "AI-driven empathy, mood detection, and advice",
    FacialExpressions: "Dynamic emotions through expressions and gestures",
    platformCompatibility: ["Web", "Mobile", "VR/AR", "Metaverse"],
    Connectivity: "Cloud-based AI with deep learning for emotions",
    useCases: [
      "Therapy",
      "Mental wellness",
      "Companionship",
      "Emotional coaching",
    ],
  },
  {
    name: "ROH-Cat-1.0",
    Description: "Customizable virtual pet name",
    Appearance: "Realistic or stylized 3D/2D cat model",
    voiceSounds: "AI-generated meows, purrs, and cat sounds",
    Languages: "Understands multiple Languages for interactions",
    Speed: "Instant reactions with real-time AI processing",
    Intelligence: "Learns behaviors, emotions, and user preferences",
    FacialExpressions: "Blinking, tail movements, ear reactions",
    platformCompatibility: ["Web", "Mobile", "VR/AR", "Metaverse"],
    Connectivity: "Cloud-based AI with API integration",
    useCases: ["Virtual pet", "Companionship", "Entertainment", "Relaxation"],
  },
  {
    name: "ROH-Sci-1.0",
    Description: "AI for blockchain and crypto insights",
    Appearance: "Futuristic 3D avatar with financial themes",
    VoiceTone: "Informative, professional, and analytical",
    Languages: "Multi-language support with finance terminology",
    Speed: "Instant crypto market updates & analysis",
    Intelligence: "AI-driven trading insights, market trend analysis",
    FacialExpressions: "Engaging, confidence-inspiring responses",
    platformCompatibility: ["Web", "Mobile", "VR/AR", "Crypto platforms"],
    Connectivity: "Real-time market data, blockchain API integration",
    useCases: ["Crypto education", "Investment guidance", "Risk assessment"],
  },
  {
    name: "ROH-Biz-1.0",
    Description: "AI-driven business assistant",
    Appearance: "Professional 2D/3D avatar with business attire",
    VoiceTone: "Formal, persuasive, and strategic",
    Languages: "Supports multiple business communication styles",
    Speed: "Instant replies with business Intelligence",
    Intelligence: "AI-powered analytics, decision support, automation",
    FacialExpressions: "Professional and confident body language",
    platformCompatibility: ["Web", "Enterprise systems", "CRM platforms"],
    Connectivity: "Cloud-based AI with ERP and CRM integration",
    useCases: ["Business analytics", "Decision-making", "Sales support"],
  },
  {
    name: "ROH-Edu-1.0",
    Description: "AI tutor for interactive learning",
    Appearance: "Friendly 2D/3D avatar with adaptive themes",
    VoiceTone: "Encouraging, patient, and educational",
    Languages: "Supports multiple Languages and subject-specific terms",
    Speed: "Real-time interactive learning assistance",
    Intelligence: "AI-driven adaptive learning, knowledge assessment",
    FacialExpressions: "Expressive reactions for engagement",
    platformCompatibility: ["Web", "Mobile", "VR/AR", "LMS platforms"],
    Connectivity: "Cloud-based AI with LMS and e-learning integration",
    useCases: ["Online tutoring", "Corporate training", "Skill development"],
  },
  {
    name: "ROH-Alpha-0.1",
    Appearance: "2D/3D human-like or stylized digital form",
    VoiceTone: "AI-generated voice with adjustable pitch, emotion",
    Languages: "Supports multiple languages with real-time translation",
    Speed: "Instant replies with low-latency AI processing",
    Intelligence: "Uses AI (LLMs, NLP) for decision-making",
    FacialExpressions: "Realistic animations for immersive interactions",
    platformCompatibility: ["Web", "Mobile", "VR/AR", "Metaverse"],
    Connectivity: "Cloud-based AI with API and real-time updates",
    useCases: ["Customer service", "Gaming", "Education", "Virtual assistants"],
  },
];

export default aiModels;
